[ixperf]
# Index-type to benchmark.
index = "bogn-llrb"

# Key-type for the index.
key_type = "i64"

# Value-type for the index
value_type = "i64"

# Block size if key-type is vector-of-bytes.
key_size = 64

# Block size if key-type is vector-of-bytes.
value_size = 64

# statistics output format
json = false

# Seed for randomization.
seed = 0

# Total number of initial load operations.
loads = 10_000_000

# Total number of incremental set operations.
sets = 10_000_000

# Total number of incremental delete operations.
deletes = 0

# Total number of get operations.
gets = 10_000_000

# Total number of full table scan.
iters = 0

# Total number of range iterations between a lower bound and upper bound.
ranges = 0

# Total number of reverse iterations between an upper bound and lower bound.
revrs = 0

[bogn-llrb]
# Whether to create index in LSM (log-structured-merge) mode.
lsm = true

# Number of reader threads.
readers = 4

# Number of writer threads.
writers = 1
