[ixperf]
# Index-type to benchmark.
index = "llrb-index"

# Key-type for the index.
key_type = "i64"

# Value-type for the index
value_type = "i64"

[generator]

# Seed for randomization.
seed = 0

# Block size if key-type is vector-of-bytes.
key_size = 64

# Block size if key-type is vector-of-bytes.
value_size = 64

# Total number of initial load operations.
loads = 1_000_000

# Total number of incremental set operations.
sets = 0

# Total number of incremental delete operations.
deletes = 0

# Total number of get operations, applied after the initial load.
gets = 0

# Total number of range iterations between a lower bound and upper bound,
# applied after the initial load.
ranges = 0

# Total number of reverse iterations between an upper bound and lower bound,
# applied after the initial load.
reverses = 0

# Benchmark a full table scan.
iters = false

# channel size to use between generator thread and loader thread. If
# channel size is <= ZERO, then index-ops shall be created asynchronously.
channel_size = 100_000

[lmdb]
name = "lmdb-ixperf"
readers = 0
writers = 1

[rdms]
name = "rdms-ixperf"
index = "shllrb"
commit_interval = 0 # in seconds.
initial = 1
readers = 0
writers = 0

[llrb-index]
# no other options other than the [ixperf]

[rdms-llrb]
# Whether to create index in LSM (log-structured-merge) mode.
lsm = false

[rdms-robt]
# Whether to create index in LSM (log-structured-merge) mode.
lsm = false

# On disk path, for index that need disk access.
path = ""
