[ixperf]
# Index-type to benchmark.
index = "lmdb"

# Key-type for the index.
key_type = "bytes"

# Value-type for the index
value_type = "bytes"

[generator]

# Seed for randomization.
seed = 0

# Block size if key-type is vector-of-bytes.
key_size = 64

# Block size if key-type is vector-of-bytes.
value_size = 400

# Total number of initial load operations.
loads = 1_000_000

# Total number of incremental set operations.
sets = 0

# Total number of incremental delete operations.
deletes = 0

# Total number of get operations, applied after the initial load.
gets = 0

# Total number of range iterations between a lower bound and upper bound,
# applied after the initial load.
ranges = 0

# Total number of reverse iterations between an upper bound and lower bound,
# applied after the initial load.
reverses = 0

# Benchmark a full table scan.
iters = false

# channel size to use between generator thread and loader thread. If
# channel size is <= ZERO, then index-ops shall be created asynchronously.
channel_size = 0

[lmdb]
name = "lmdb-ixperf"
readers = 0
writers = 1
load_batch = 100_000

[rdms]
name = "rdms-ixperf"
index = "shllrb"
commit_interval = 0 # in seconds.
initial = 1
readers = 0
writers = 0

[llrb-index]
# no other options other than the [ixperf]

[rdms-llrb]
# create llrb with log-structured-merge.
lsm = false
# create llrb in sticky mode.
sticky = false
# spin while waiting for lock
spin = true

[rdms-mvcc]
# create llrb with log-structured-merge.
lsm = false
# create llrb in sticky mode.
sticky = false
# spin while waiting for lock
spin = true

[rdms-shllrb]
# create llrb with log-structured-merge.
lsm = false
# create llrb in sticky mode.
sticky = false
# spin while waiting for lock
spin = true
# aut-shard interval in seconds
interval = 30
# maximum number of shards allowed.
max_shards = 1024
# maximum number of entries beyond which shard shall be split.
max_entries = 1_000_000

[rdms-robt]
dir = "./data"
z_blocksize = 4096
m_blocksize = 4096
v_blocksize = 4096
delta_ok = true
vlog_file = ""
value_in_vlog = true
flush_queue_size = 64
mmap = true
bitmap = "nobitmap"
